# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# .github/workflows/maven.yml
name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    strategy:
      matrix:
        architecture: [ arm64 ]

    steps:
      - uses: actions/checkout@v4
      - name: Check system information
        run: |
          echo "Operating System: $(uname -a)"
          echo "Architecture: $(uname -m)"
          echo "Distribution: $(lsb_release -d)"
          echo "mvn version: $(mvn --version)"
      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'graalvm'
          cache: maven
      - name: Build with Maven
        run: mvn test -Dtest=EmbeddingTest#testFail --file pom.xml
